### ISSUE TITLE
ModuleNotFoundError: No module named 'mask'

### ISSUE THREAD

**Issue by SherlockHolmes221** [s-gupta/v-coco#4]
ModuleNotFoundError: No module named 'mask' in  coco/PythonAPI/pycocotools/coco.py

**Comment by rebeen** [comment]
I have the same error, did you solve this problem?

**Comment by SherlockHolmes221** [comment]
I solved it by changing the code in coco/PythonAPI/pycocotools/coco.py
change import mask to from . import mask
Hope it helps

**Comment by rebeen** [comment]
Thank ou but now I have this problem 

Traceback (most recent call last):
  File "PythonAPI/setup.py", line 23, in <module>
    cythonize(ext_modules)
  File "/home/rebeen/anaconda3/envs/env/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 966, in cythonize
    aliases=aliases)
  File "/home/rebeen/anaconda3/envs/env/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 810, in create_extension_list
    for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
  File "/home/rebeen/anaconda3/envs/env/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 109, in nonempty
    raise ValueError(error_msg)
ValueError: 'pycocotools/_mask.pyx' doesn't match any files
