### ISSUE TITLE
   np.array(vsrl_data[i]['role_object_id']).reshape((len(vsrl_data[i]['role_name']),-1)).T KeyError: 'role_object_id'

### ISSUE THREAD

**Issue by monacv** [s-gupta/v-coco#9]
```
(vcoco) mona@goku:~/research/code/v-coco$ python demo_vcoco.py 
added /home/mona/research/code/v-coco/coco/PythonAPI to pythonpath
loading annotations into memory...
Done (t=1.12s)
creating index...
index created!
Traceback (most recent call last):
  File "demo_vcoco.py", line 28, in <module>
    vcoco_all = vu.load_vcoco('vcoco_train')
  File "/home/mona/research/code/v-coco/vsrl_utils.py", line 46, in load_vcoco
    np.array(vsrl_data[i]['role_object_id']).reshape((len(vsrl_data[i]['role_name']),-1)).T
KeyError: 'role_object_id'
```

here is the code:

```
import __init__
import vsrl_utils as vu
import numpy as np

import matplotlib
import matplotlib.pyplot as plt

def draw_bbox(plt, ax, rois, fill=False, linewidth=2, edgecolor=[1.0, 0.0, 0.0], **kwargs):
    for i in range(rois.shape[0]):
        roi = rois[i,:].astype(np.int)
        ax.add_patch(plt.Rectangle((roi[0], roi[1]),
            roi[2] - roi[0], roi[3] - roi[1],
            fill=False, linewidth=linewidth, edgecolor=edgecolor, **kwargs))

##def subplot(plt, (Y, X), (sz_y, sz_x) = (10, 10)):
def subplot(plt, yx, sz = (10, 10)):
    (Y, X) = yx
    (sz_y, sz_x) = sz
    plt.rcParams['figure.figsize'] = (X*sz_x, Y*sz_y)
    fig, axes = plt.subplots(Y, X)
    return fig, axes


# Load COCO annotations for V-COCO images
coco = vu.load_coco()

# Load the VCOCO annotations for vcoco_train image set
vcoco_all = vu.load_vcoco('vcoco_train')
for x in vcoco_all:
    x = vu.attach_gt_boxes(x, coco)


```

![Screenshot from 2021-04-05 18-11-40](https://user-images.githubusercontent.com/76495162/113633151-73342980-963a-11eb-84fb-391eaac13996.png)

**Comment by monacv** [comment]
`dict_keys([b'image_id', b'ann_id', b'role_object_id', b'label', b'action_name', b'role_name', b'include'])`


so

comment this line `vsrl_data = unicode_to_str(vsrl_data)` in the following method:

```
def load_vcoco(imset, dir_name=None):
  if dir_name is None:
    dir_name = get_data_dir()
  with open(os.path.join(dir_name, 'vcoco', imset + '.json'), 'rt') as f:
    vsrl_data = json.load(f)
  #vsrl_data = unicode_to_str(vsrl_data)
```

in `vsrl_utils.py`
